### PR TITLE
Implemented all commands

### PR DESCRIPTION
**Pull request by konikvranik**
I implemented all known Rainbird commands in RainbirdController class and covered it by tests.

### CODE REVIEW

**Comment by konikvranik** [comment]
@jbarrancos Hello, may I ask you for another merge and publish round?
I implemented all known endpoinds, added tests and improved return data

**Comment by jbarrancos** [comment]
Thx

**Comment by jbarrancos** [comment]
Done

**Comment by konikvranik** [comment]
Great! Thank you.

**Pull request merged**
