### PR TITLE
Add support for controllers with more than eight zones.

### PR DESCRIPTION
**Pull request by jlinford**

### CODE REVIEW

**Comment by peternijssen** [comment]
@jbarrancos Any update on his PR? (+ other open issues?)

**Comment by jbarrancos** [comment]
I’ll try to merge it tomorrow.

Op 19 jul. 2020 om 16:32 heeft Peter Nijssen <notifications@github.com> het volgende geschreven:

﻿

@jbarrancos<https://github.com/jbarrancos> Any update on his PR? (+ other open issues?)

**Comment by peternijssen** [comment]
Can it also be build towards pypi so we can actually update HA?

**Comment by jbarrancos** [comment]
Updated version 0.4.2

**Pull request merged**
