### PR TITLE
Support for controller model names

### PR DESCRIPTION
**Pull request by konikvranik**
1. `get_model_and_version` now returns also model name and model code.
2. fixed typo
3. description files are now in yaml

### CODE REVIEW

**Comment by konikvranik** [comment]
@jbarrancos Hi there, may I ask you to merge this PR?

**Comment by jbarrancos** [comment]
Thx!

**Comment by konikvranik** [comment]
@jbarrancos Do you plan a new release?

**Comment by jbarrancos** [comment]
https://pypi.org/project/pyrainbird/0.5.0/

**Comment by konikvranik** [comment]
Great, thank you!

**Pull request merged**
